import DuelistAlgorithm
import FireflyAlgorithm
import GeneticAlgorithm
import GravitationalSearchAlgorithm
import GreyWolfOptimizer
import MultiVerseOptimizer
import ParticleSwarmOptimization
import SimulatedAnnealing